### ISSUE TITLE
[10:24:35 WARN]: [RaspberryJuice] Task #2 for RaspberryJuice v1.12.1 generated an exception

### ISSUE THREAD

**Issue by nootkroot** [zhuowei/RaspberryJuice#103]
When trying to ping or connect to the server, it will say stuff like "Starting input thread" and "Starting output thread!" and then give me the error [10:24:35 WARN]: [RaspberryJuice] Task #2 for RaspberryJuice v1.12.1 generated an exception. Also it would be really nice if someone also helped me with the mcpi module since it isn't working properly at all even though I followed literally every step everyone out there is saying.

**Comment by martinohanlon** [comment]
You have closed this issue. Does that mean you have resolved the issue.

**Comment by nootkroot** [comment]
Yes, I forgot I changed the server IP to be hosted on the same port as RaspberryJuice cause I was having difficulties with mcpi so I changed it back to the default and it was fixed. Also changing it back to default somehow also fixed the problem I had with mcpi even though it wasn't working before I changed it to the same port as RaspberryJuice.
