### ISSUE TITLE
Missing aliases for WATER and LAVA in block.py

### ISSUE THREAD

**Issue by OrlandoRichards** [zhuowei/RaspberryJuice#21]
The aliases for WATER and LAVA (to WATER_FLOWING and LAVA_FLOWING) are missing from block.py.

Easy to fix:

    diff --git a/src/main/resources/mcpi/api/python/mcpi/block.py b/src/main/resources/mcpi/api/python/mcpi/block.py
    index 1e72d3e..893788b 100644
    --- a/src/main/resources/mcpi/api/python/mcpi/block.py
    +++ b/src/main/resources/mcpi/api/python/mcpi/block.py
    @@ -26,8 +30,10 @@ WOOD_PLANKS         = Block(5)
     SAPLING             = Block(6)
     BEDROCK             = Block(7)
     WATER_FLOWING       = Block(8)
    +WATER               = WATER_FLOWING
     WATER_STATIONARY    = Block(9)
     LAVA_FLOWING        = Block(10)
    +LAVA                = LAVA_FLOWING
     LAVA_STATIONARY     = Block(11)
     SAND                = Block(12)
     GRAVEL              = Block(13)

**Comment by martinohanlon** [comment]
I have updated block.py to the latest version from the pi api 1.1. Thanks
