### ISSUE TITLE
setBlock() not working in Minecraft 1.8

### ISSUE THREAD

**Issue by skybutter** [zhuowei/RaspberryJuice#23]
I used Bukkit 1.8.  RaspberryJuice 1.6.  setBlock() not working.  Nothing happened.  Nothing in the console either.

**Comment by martinohanlon** [comment]
I have just retested with a CraftBukkit 1.8 and Spigot 1.8 build from the 3rd Feb and everything worked fine. Any errors in Python? Any plugins with world protection.

**Comment by martinohanlon** [comment]
Just because Im paranoid, I just rebuilt CraftBukkit from the latest build and again tested with no issues.

Do you know that raspberry juice co-ordinates are relative to spawn? So if you were trying setBlock(0,0,0,1) and went to the co-ordinate 0,0,0 shown on the Minecraft it wouldnt be the same!?

**Comment by skybutter** [comment]
When I tried it, I was not in the default world.  I have the multiworld plugin.  I moved to another world I created.  There, the setBlock() did not do anything.  But when i switched back to the default work, the setBlock() worked.  Do you know why?  Would it only work in the default world.  Thanks.

**Comment by martinohanlon** [comment]
I see. RaspberryJuice isnt 'multi world' compatible and 'world' functions only work on the default world. There is an open enhancement which has requested it. https://github.com/zhuowei/RaspberryJuice/issues/8
