### ISSUE TITLE
The function getBlocks doesn't do what it tells to do

### ISSUE THREAD

**Issue by vencejo** [zhuowei/RaspberryJuice#28]
Hi , first of all , greetings for your great job in this repo.

Secondly , tell you that the getBlocks function doesn't return a list as it's comment tells, it actually returns an integer.

I try to fix it with this code that works in Minecraft of PC but doesn't work in Minecraft Pi

```
   def getBlocks(self, *args):
          """Get a cuboid of blocks (x0,y0,z0,x1,y1,z1) => [id:int]"""
          blocksInString = self.conn.sendReceive("world.getBlocks", intFloor(args))
          listStringBlocks = blocksInString.split(',')
	      listOfBlocks = [int(block) for block in listStringBlocks] 
          return listOfBlocks
 ```

**Comment by martinohanlon** [comment]
getBlocks should return a string and integers with a comma seperator. getBlocks was never implemented in the Pi edition, so this is an interpretation.
