### ISSUE TITLE
Please add support for older Java 1.6.0.jdk that comes supplied by Apple on OS X

### ISSUE THREAD

**Issue by Basilmir** [zhuowei/RaspberryJuice#30]
I recently encountered this problem as I already had Java installed on my Mac. Everything ran except RaspberryJuice which failed with an error not supporting major.minor 52.

Would it be possible to compile it to that so we can get wider support on the Mac without the overhead of having users manually remove Apple supplied Java and install the newest version?

Thank you.

For a more detailed explanation see: http://stackoverflow.com/questions/33976549/minecraft-on-os-x-port-4711-connection-refused/33979105#33979105

**Comment by martinohanlon** [comment]
RaspberryJuice is already built with Java 1.6. What version of OS X are you running? 

![image](https://cloud.githubusercontent.com/assets/2329501/11456205/8bfabdf6-9679-11e5-8d06-3cde43d9e85d.png)

This is the first time I have ever had this issue reported, and I know there are a lot of Mac users, including myself.

**Comment by martinohanlon** [comment]
No updated, closing,
