### ISSUE TITLE
world.getplayerIds() not working

### ISSUE THREAD

**Issue by twoyoon** [zhuowei/RaspberryJuice#33]
I'm on 1.9 minecraft with bukkit plugins permissionEx and ShellReact.

I'm working with a multiplayer world, so I understand that player.getPos() will not work.  But entity.getPos() should. Right?

But I can't get the player ID from the world.getplayerIds() command.  It doesn't work.

The setBlock commands work so I can create blocks.  

Any suggestions?

**Comment by martinohanlon** [comment]
New version RaspberryJuice 1.8 released... Fixed issues with Minecraft 1.9. Thanks for the info.
