### ISSUE TITLE
Bukkit alternative?

### ISSUE THREAD

**Issue by neuhaus** [zhuowei/RaspberryJuice#37]
Is the bukkit project dead?There was a DMCA takedown...
If so, is there an alternative way to use Raspberry Juice?

If not, where can I get it?

What's required to get Raspberry Juice to work with Minecraft 1.10.x?

**Comment by martinohanlon** [comment]
Bukkit was 'picked up' by Spigot https://www.spigotmc.org/

You can get RaspberryJuice here https://www.spigotmc.org/resources/raspberryjuice.22724/

I havent tested with 1.10, but I dont see any reason why it wouldnt work.

I also ported RaspberryJuice to canarymod https://github.com/martinohanlon/CanaryRaspberryJuice - although canarymod doesnt looks like its being updated.

There is also a forge implementation Raspberry Jam Mod - https://github.com/martinohanlon/CanaryRaspberryJuice

**Comment by neuhaus** [comment]
Thanks. I managed to build Spigot for 1.10.2.

I think 1.10 introduced new block types (where can we get a list?) and they should be added to `src/main/resources/mcpi/api/python/original/mcpi/block.py`.

Thanks for your work!
