### ISSUE TITLE
Extra data for world.setBlock(x, y, z, block.type, [data]) not working

### ISSUE THREAD

**Issue by neuhaus** [zhuowei/RaspberryJuice#38]
I'm not sure this is a bug, perhaps I'm just doing something wrong?

It appears that no matter that extra parameter I give, the ladders always are attached to the north wall.

    world.setBlock(x, y, z, block.LADDER, 2)
    world.setBlock(x, y, z, block.LADDER, 3)
    world.setBlock(x, y, z, block.LADDER, 4)
    world.setBlock(x, y, z, block.LADDER, 5)
    world.setBlock(x, y, z, block.LADDER)

all have the same effect: If there is a wall to the north, the ladder is attached to it. If there isn't, the ladder appears as a floating item that can be picked up.

According to http://minecraft.gamepedia.com/Ladder#Block_data the extra parameter should be the direction, right?

I'm using a server running spigot 1.10.2 and raspberryjuice 1.8

Thanks.

**Comment by neuhaus** [comment]
Here is a sample listing that shows this issue:

```
import mcpi.minecraft as minecraft
import mcpi.block as block

world = minecraft.Minecraft.create()
[x,y,z] = world.player.getPos()

for direction in range(2,6):
	world.setBlock(x, y, z, block.DIRT)
	world.setBlock(x+1, y, z, block.DIRT)
	world.setBlock(x+2, y, z, block.DIRT)
	world.setBlock(x, y, z+1, block.DIRT)
	world.setBlock(x+2, y, z+1, block.DIRT)
	world.setBlock(x, y, z+2, block.DIRT)
	world.setBlock(x+1, y, z+2, block.DIRT)
	world.setBlock(x+2, y, z+2, block.DIRT)
	world.setBlock(x+1, y, z+1, block.LADDER, direction) # place ladder last
	x+=3
   
print("Go back to Minecraft and look at the ladders in the holes")
```

**Comment by neuhaus** [comment]
I have the same issue with the extra parameter for wool blocks that normally specifies the colour. It gets ignored and all wool blocks I create are white.

I'm using python 2.7.11.

**Comment by martinohanlon** [comment]
You need to explicitly pass the block id and the data value.

e.g.

    mc.setBlock(x, y, z, block.WOOL.id, 1)

Otherwise the python library assumes you are passing a block object the constants for which have 0 as the data value.

You could create your own block as well.

    orange_wool = block.Block(35, 1)
    mc.setBlock(x, y, z, orange_wool)

... or something like this.

**Comment by martinohanlon** [comment]
This api reference might be useful - it has examples of how to use the api calls http://www.stuffaboutcode.com/p/minecraft-api-reference.html

**Comment by neuhaus** [comment]
Thanks. That's useful. However it looks as if I am doing it correctly yet it doesn't work.

**Comment by neuhaus** [comment]
Thanks!

**Comment by martinohanlon** [comment]
In the code snippets you provided you haven't put the .id on the block type. Have you added this? If so can you give me a code listing + info about your setup (Minecraft version, server setup, Bukkit version, etc)

**Comment by neuhaus** [comment]
Yep, it works now.. thanks a bunch!
