### ISSUE TITLE
Python API Error

### ISSUE THREAD

**Issue by kartoffelx86** [zhuowei/RaspberryJuice#41]
Hello there.
I'm always getting an error when trying to use the python api.
`Traceback (most recent call last):
  File "C:\Users\julia_000\Documents\Python\mcpi_tests\mc.py", line 3, in <module>
    print(mc.getPlayerEntityIds())
  File "C:\Users\julia_000\Documents\Python\mcpi_tests\mcpi\minecraft.py", line 186, in getPlayerEntityIds
    ids = self.conn.sendReceive("world.getPlayerIds")
  File ".\mcpi\connection.py", line 49, in sendReceive
    self.send(*data)
  File ".\mcpi\connection.py", line 38, in send
    self.socket.sendall(s)
TypeError: a bytes-like object is required, not 'str'`

I tried to fix it myself, but I'm not getting any further.
Does anyone know how to fix this error or is the api just broken?

Best Regards,
Julian

**Comment by kartoffelx86** [comment]
Oh, and I'm running Python 3.5.2

**Comment by martinohanlon** [comment]
Try running Python 2.x,

Or, have a look at https://github.com/shawill/py3minepi for a python 3 compatible library.

**Comment by gregs007** [comment]
py3minepi doesn't support the raspberryjuice additional features/methods. Any plans on maybe forking py3minepi and porting the raspberryjuice features over to it?

**Comment by martinohanlon** [comment]
one step ahead of you https://github.com/martinohanlon/py3minepi

**Comment by martinohanlon** [comment]
I will get this into the resources in RaspberryJuice

**Comment by gregs007** [comment]
Oh that's perfect... Thank you!

**Comment by martinohanlon** [comment]
It seems I had already done it...  but left the change in `dev`, Ive just merged it into `master`.

**Comment by gregs007** [comment]
Perfect, thank you. One more thing and to post it here, but can't post issue to the fork: Noticed that the 3rd argument to create() (name) is missing. Pretty handy and was wondering if you planned on implementing in py3 version? Thanks for all you've done-- teaching my kids python and this is so much fun.

**Comment by martinohanlon** [comment]
I was planning on removing the functionality to use name in .create to target a particular player. It was only originally put in (not by me) because RaspberryJuice didnt suport the `.entity' functions.

You can use the alternative:

```
mc = Minecraft.create()
playerid = mc.getPlayerEntityId("martinohanlon")
mc.entity.setPos(playerid, x, y, z)
```

The benefit of using this is that you can interact with any player, not use the one you specify in the connection.  This is also inline with the Pi edition API.

**Comment by gregs007** [comment]
Makes a lot of sense. Thanks for the reply!
