### ISSUE TITLE
Don't Put Releases In Source Code

### ISSUE THREAD

**Issue by opticyclic** [zhuowei/RaspberryJuice#43]
Releases should be published on the GitHub releases section instead of being in the jars directory.

When there is a release, the code should be tagged in git and the maven binary published on the releases page.

This has benefit of the repo being smaller and the source code of each release linked to the binary.

It is possible to retrospectively create the tags in git meaning you can delete the current jars in the jars dir.

**Comment by martinohanlon** [comment]
Thanks for the advice, but I dont want to change the structure of such an established project.
