### ISSUE TITLE
getPlayerEntityId fail when the user requested does not exist.

### ISSUE THREAD

**Issue by dglaude** [zhuowei/RaspberryJuice#56]
This program test the function mc.getPlayerEntityId in two case.

Case 1: The user "Present" that is connected to the server => OK
Case 2: The user "Absent" that is not connected to the server => KO

```python
# http://eu.wiley.com/WileyCDA/WileyTitle/productCd-111894691X.html

# The Minecraft API has to be imported before it can be used
import mcpi.minecraft as minecraft

# To communicate with a running Minecraft game, you need a connection to that game.
mc = minecraft.Minecraft.create()

# Getting the list of entity (players) in the game
entityIds = mc.getPlayerEntityIds()

# For all entity (player) display their position
for entityId in entityIds:
    pos = mc.entity.getPos(id=entityId)
    mc.postToChat("entityId="+str(entityId)+"x="+str(pos.x) + " y="+str(pos.y) +" z="+str(pos.z))

mc.postToChat("+++ath 1")

# This should get the Id of user "Present"
PresentId = mc.getPlayerEntityId("Present")
mc.postToChat("Present="+str(PresentId))

mc.postToChat("+++ath 2")

# This should get the Id of user "Absent"
AbsentId = mc.getPlayerEntityId("Absent")
mc.postToChat("Absent="+str(AbsentId))

mc.postToChat("+++ath 3")

# END
```

Here is the result server side, no error, just an INFO but the "+++ath 3" is never reached:

```
[21:02:51 INFO]: [RaspberryJuice] Opened connection to/127.0.0.1:34183.
[21:02:51 INFO]: [RaspberryJuice] Starting input thread
[21:02:51 INFO]: [RaspberryJuice] Starting output thread!
[21:02:51 INFO]: entityId=14x=128.5 y=66.0 z=144.5
[21:02:51 INFO]: +++ath 1
[21:02:51 INFO]: Present=14
[21:02:51 INFO]: +++ath 2
[21:02:51 INFO]: [RaspberryJuice] Player [Absent] not found.
```

Here is the result client side where an Traceback is given for the call with the unexisting (not connected) user:

```
>>> %Run PresentAbsent.py
Traceback (most recent call last):
  File "/home/pi/AdventuresInMinecraft-Mac/MyAdventures/PresentAbsent.py", line 26, in <module>
    AbsentId = mc.getPlayerEntityId("Absent")
  File "/home/pi/AdventuresInMinecraft-Mac/MyAdventures/mcpi/minecraft.py", line 185, in getPlayerEntityId
    return int(self.conn.sendReceive(b"world.getPlayerId", name))
  File "/home/pi/AdventuresInMinecraft-Mac/MyAdventures/mcpi/connection.py", line 63, in sendReceive
    return self.receive()
  File "/home/pi/AdventuresInMinecraft-Mac/MyAdventures/mcpi/connection.py", line 57, in receive
    raise RequestError("%s failed"%self.lastSent.strip())
mcpi.connection.RequestError: b'world.getPlayerId(Absent)' failed
>>> 
```

I believe a gracefully return should be provided if the name used is not connected.

**Comment by dglaude** [comment]
The problem might be in mcpi and to be fixed there and not in RaspberryJuice.

It is possible to catch this exception to work around this problem like this:

try:
    AbsentId = mc.getPlayerEntityId("Absent")
except:
    mc.postToChat("Exception catched")
    AbsentId = 0

mc.postToChat("Absent="+str(AbsentId))

**Comment by martinohanlon** [comment]
Ok, so what happens here is that RaspberryJuice is returning "Fail", in the event that the player isn't logged in. Returning "Fail" is 'sort of' Minecraft Pi's 'usual' way of returning an error. Although the mcpi python library doesn't really handle these 'fails' very well and simply errors.

So I can either assume this as being 'standard' way the mcpi library works or I could change RaspberryJuice to return -1 in the event of a not finding a player, but this doesnt feel right....  Opinions?

**Comment by martinohanlon** [comment]
I am going to leave this as is. The API will return FAIL, which is consistent with other functions.
