### ISSUE TITLE
Test.py hangs on Hit a block

### ISSUE THREAD

**Issue by timcu** [zhuowei/RaspberryJuice#58]
I tried left clicking and right clicking in survival or creative and it would not go past this step in the test. I even changed hitclick to BOTH in config.yml. I am running Minecraft 1.12 in Spigot server

**Comment by martinohanlon** [comment]
Are you holding a sword?

**Comment by timcu** [comment]
No I wasn't. I tried hitting a block with a sword and test continued fine. Thanks. Maybe it would help if the instruction was "Hit a block with a sword"
