### ISSUE TITLE
python version compatability?

### ISSUE THREAD

**Issue by neuhaus** [zhuowei/RaspberryJuice#61]
Hi,

could you clarify the python version required in the README?
I know that it works with python 2.x, is it also python 3.x compatible?

**Comment by martinohanlon** [comment]
The python libraries at https://github.com/zhuowei/RaspberryJuice/tree/master/src/main/resources/mcpi/api/python are both Python 2 and 3 compatible. Obviously you don't have to use these libraries with RaspberryJuice, you can use whatever library you want that supports the API.
