### ISSUE TITLE
getRotation() returns negative values

### ISSUE THREAD

**Issue by neuhaus** [zhuowei/RaspberryJuice#62]
I'm getting values from -360 to 0 on Minecraft 1.12.2 instead of 0..360 as written in the documentation.

**Comment by neuhaus** [comment]
There seems to be an issue that I think is likely to be related:
Sometimes the players' rotation is limited when using a server running RaspberryJuice.

**Comment by martinohanlon** [comment]
I haven't had a look at this issue yet. But can you clarify "Sometimes the players' rotation is limited when using a server running RaspberryJuice." 

Where have you seen this noted? This has never been mentioned before and I'm struggling to see how this would be the case, there is nothing within RaspberryJuice which would have this effect.

**Comment by neuhaus** [comment]
Well I was playing around on a local server with RaspberryJuice and I used getRotation() and sometimes I was unable to rotate (using the mouse) beyond a certain point.
I think restarting the client fixed the problem - which may or may not indicate that it's a client issue.

Anyway, this occured more than once.

**Comment by martinohanlon** [comment]
Ok... Just did some investigation.

In turns out that Minecraft returns rotational values as -360-0 - all RaspberryJuice does is simply pass these out.

I was half tempted to leave it as-is given this is how Minecraft represents numbers, but I can understand its a bit weird... Ill fix in the next release.

**Comment by martinohanlon** [comment]
in 1.10.1
