### ISSUE TITLE
RaspberryPi mcpi python updates do no work

### ISSUE THREAD

**Issue by s21825** [zhuowei/RaspberryJuice#70]
I just noticed that there were some updates to the modded mcpi python api in your project so I downloaded it to try them out. Many of the new addtions do not function:

spawnEntity
getBlocks
pollChat
etc

These don't seem to be available on the Raspberry Pi Minecraft so I'm not sure they should be included in the modded api. I'm running Raspbian from a Dec 2017 download.

Perhaps I'm missing something?

**Comment by zhuowei** [comment]
@s21825 The new additions are intended to be used with the RaspberryJuice plugin on a Java edition server, not on the actual Pi edition. I guess that can be clarified in the documentation?

**Comment by s21825** [comment]
@zhuowei Ahh! Makes sense. I thought mcpi was for the Pi only. Thanks for clarifying.
