### ISSUE TITLE
Multiple connections on a remote server

### ISSUE THREAD

**Issue by JasonZ321** [zhuowei/RaspberryJuice#74]
Hi, I 'm programming teacher. Trying to use Spigot + RaspberryJuice to teach students Python.
The idea is to deploy a spigot server with RaspberryJuice as plugin on my own server, and let students connect and hacking with python scripts on the same server. But I found students' scripts weren't work when multiple connections on the same time.
I wonder if there is a configuration for this or it simply does not allow multiple connections on the same time.
Does anyone can help with this?

**Comment by adsznzhang** [comment]
I am facing the same problem and trying to figure out how to solve this one. It should be a issue with the RaspberryJucie plugin. At the moment it only accepts code from localhost rather than other computers from LAN. I am keen to learn how to solve this problem if anyone can help. Really appropriate!

**Comment by adsznzhang** [comment]
> Hi, I 'm programming teacher. Trying to use Spigot + RaspberryJuice to teach students Python.
> The idea is to deploy a spigot server with RaspberryJuice as plugin on my own server, and let students connect and hacking with python scripts on the same server. But I found students' scripts weren't work when multiple connections on the same time.
> I wonder if there is a configuration for this or it simply does not allow multiple connections on the same time.
> Does anyone can help with this?

Did you try this ? https://github.com/zhuowei/RaspberryJuice/pull/71

**Comment by martinohanlon** [comment]
Hi, I have only just seen this issue. Apologies

I suspect you have 2 different problems, so I will reply in 2 different threads.

**Comment by martinohanlon** [comment]
@JasonZ321 when you say the scripts didnt work can you provide more information? 

The key thing to be aware of when using multiple connections to the server is that if you use the mc.player.functions (getPos, setPos, etc) it will only work with the "host" player (usually the player who connected to the server first).

To work with multiple players on the same server your scripts should use the mc.entity.functions so you can specify which player you want to interact with.

Have a look at the API reference here - https://www.stuffaboutcode.com/p/minecraft-api-reference.html

**Comment by martinohanlon** [comment]
Im closing as there has been no response.
