### ISSUE TITLE
events.projectile.hits missing

### ISSUE THREAD

**Issue by Marcinosoft** [zhuowei/RaspberryJuice#75]
Is it possible to implement "events.projectile.hits" command ?
I saw it within https://github.com/TeachCraft/TeachCraft-Examples/tree/master/mcpi
which works with forked RaspberryJuice https://github.com/TeachCraft/RaspberryJuice

**Comment by RonTang** [comment]
Hi Marcinosoft, I add this feature in my fork repo https://github.com/RonTang/RaspberryJuice. I also build a jar which name 1.12 for this feature. I hope this can help you.

**Comment by Marcinosoft** [comment]
Hi RonTang. I missed your reply till today. I will check it for sure. It also would be nice to pull merge request to this repository as long forking is fine, but in my opinion one project with all functionalities project is better.

**Comment by martinohanlon** [comment]
I'm away at the moment, I will look into this and other PRs when I return.

**Comment by Marcinosoft** [comment]
Hi @RonTang - many, many thanks, it works. I made small fixes and addons related to pollProjectileHits implementation. If you are interested you can look into my fork:
https://github.com/Marcinosoft/RaspberryJuice
I really wanted to pool events in scope specified player only, not events from all players, so I allow to specify optional player's entityId param for all existing event related methods.

I really hope that @martinohanlon will merge valuable pull requests soon, because it would be better to have one rich project instead of many individual forks.

**Comment by RonTang** [comment]
@Marcinosoft  I glad this can help you. thanks your comment.
