### ISSUE TITLE
Query player name?

### ISSUE THREAD

**Issue by petterreinholdtsen** [zhuowei/RaspberryJuice#76]
Hi.  Is there a way to use this API to get the names of the currently logged in users?  I would like to extract their positions and plot it on a map, and track players movement across connections.  The player ID changes between connections.

**Comment by Marcinosoft** [comment]
from mcpi.minecraft import Minecraft
mc = Minecraft.create()
for id in mc.getPlayerEntityIds():
    print(mc.entity.getName(id) + '\t[entityId = ' + str(id) + ']')

**Comment by Marcinosoft** [comment]
from mcpi.minecraft import Minecraft
mc = Minecraft.create()
for id in mc.getPlayerEntityIds():
   print(mc.entity.getName(id) + '\t[entityId = ' + str(id) + ']')

**Comment by petterreinholdtsen** [comment]
Thank you very much for the quick reply.  I tried this approach but got this exception:

AttributeError: 'CmdEntity' object has no attribute 'getName'

I guess we have different editions of the mcpi library.  Mine come from https://github.com/sprintingkiwi/pycraft_mod/.  Where do your come from?

**Comment by Marcinosoft** [comment]
It's quite obvious, that mine comes from this repository (https://github.com/zhuowei/RaspberryJuice)
I'm using latest available Bukkit/Spigot plugin: https://github.com/zhuowei/RaspberryJuice/blob/master/jars/raspberryjuice-1.11.jar
with these Python modules:
https://github.com/zhuowei/RaspberryJuice/tree/master/src/main/resources/mcpi/api/python/modded/mcpi

If you are using https://github.com/sprintingkiwi/pycraft_mod which is forked from https://github.com/arpruss/raspberryjammod-minetest that means, you are using standalone mod dedicated to game called Minetest, not Minecraft. There is also standalone mod dedicated to Minecraft here: https://github.com/arpruss/raspberryjammod, but it's dedicated to single player only. It also have some api limitations compared to server side plugin RaspberryJuice.

So, first of all, are you playing Minetest or Minecraft ?

**Comment by petterreinholdtsen** [comment]
I am playing with Minecraft with RaspberryJuice (raspberryjuice-1.11.jar) on a spigot server.

The reason I use the mcpi library included with the minetest module is that it is included by default in Debian, and I believed until you replied that the various copies of the mcpi library were the same/compatible.  But apparently, there are heaps of different versions of this library using the same namespace, making it hard to know which version is provided.

When that is said, I tried calling ```mc.conn.sendReceive(b"entity.getName", id)```, I get an error message and a mcpi.connection.RequestError exception.  Not sure how to debug it, though. :)

**Comment by Marcinosoft** [comment]
Well, If you're using Spigot with raspberryjuice-1.11.jar, with mcpi modded modules (https://github.com/zhuowei/RaspberryJuice/tree/master/src/main/resources/mcpi/api/python/modded/mcpi), at least one player is connected to game  server and mc.entity.getName(id) does not work - it's strange.
Maybe your player name contains non-ascii charactes or something.
Maybe something is written to Spigot console ?

Is sample working when you remove getName method ?

from mcpi.minecraft import Minecraft
mc = Minecraft.create()
for id in mc.getPlayerEntityIds():
    print(str(id))

What Spigot version are you using ? I'm using 1.12.2 (Implementing API version 1.12.2-R0.1-SNAPSHOT).

**Comment by petterreinholdtsen** [comment]
By adding some debug output, I managed to figure out what the problem was.  Combining python 3 with binary strings did not work well.  The command sent over to the server ended up was "b'entity.getName'(123142)", which RaspberryJuice not surprisingly did not handle well.  Using ```mc.conn.sendReceive('entity.getName', entity_id)``` instead solved my problem.  Thank you for bearing with me.
