### ISSUE TITLE
New Id Block in Minecraft Windows - Python - RaspberryJuice - Bukkit

### ISSUE THREAD

**Issue by theo55** [zhuowei/RaspberryJuice#77]
Hi,

I was used to play with Python and Minecraft on Raspberry pi.

Then I have bought a PC Windows Minecraft. I have install a local server  [ bukkit 12.2.2 with RaspberryJuice (on my PC to play and program alone and on a Raspberry pi to play in the same world and to programm in python with friends through a local network) ] : All Is fine !

I feel frustrate because I can't use new blocks with ID like bed 355 or prismarine 168, ... that exist in new minecraft (version 1.12.2 of my server). I don't understand where is the limit : 
- in RaspberryJuice I've read the .java and I've not find out where is the limitation (Id blocks are integer, It's not a troncation pb),  ? 
- In bukkit ?

Is there a way for me (perhaps in .java modifications, but which ones ?) to succeed to use new blocks ?

As someone got an idea ?

Thanks !

**Comment by martinohanlon** [comment]
Hi @theo55 

New blocks dont exist in the block python library e.g. `block.PRISMARINE`, but you can just pass the id as an integer.

e.g.

```python
mc.setBlock(x, y, z, 168)
```

![2019-09-30_16 31 28](https://user-images.githubusercontent.com/2329501/65893376-c4a58d80-e39f-11e9-91cc-64f06fd2eda6.png)
