### ISSUE TITLE
Block ID is not working in 1.14.4

### ISSUE THREAD

**Issue by gogir** [zhuowei/RaspberryJuice#81]
HI,I was used to play with Python and Minecraft  1.14.4 on Raspberry pi.

It's not working llik this:
`mc.setBlock(pos.x + 1, pos.y + 1, pos.z + 1, block.IRON_BLOCK)`

But it's ok like this:
`mc.setBlock(pos.x + 1, pos.y + 1, pos.z + 1, "IRON_BLOCK")`

BLOCK ID can't be used anymore?

Thanks!

**Comment by Howard-C** [comment]
Try `block.IRON_BLOCK.id`?

**Comment by gogir** [comment]
> Try `block.IRON_BLOCK.id`?

It can made a block,but it's not IRON_BLOCK,all int number made only one type block.

But in 1.12.2,it works.

**Comment by martinohanlon** [comment]
@gogir I have run the complete set of tests against 1.14.4 and I cant recreate this error.

![2019-09-30_16 17 26](https://user-images.githubusercontent.com/2329501/65892980-1dc0f180-e39f-11e9-8b1b-215d90202715.png)

Im not sure what you are doing with:

```
mc.setBlock(pos.x + 1, pos.y + 1, pos.z + 1, "IRON_BLOCK")
```

but this generates a run time error in the Python library as the block id has to be a integer.

Im going to close. If you can provide some additional information such as error messages, screenshot, complete code listing that may help debug. Im happy to reopen.
