### ISSUE TITLE
mc.postToChat("Message") doesn't send to ingame chat, ony visible in server chat.

### ISSUE THREAD

**Issue by Fishh40** [zhuowei/RaspberryJuice#89]
Hi There,

I'm actually struggeling with something very basic, and I can't find any information on the web about it. So Let's try it here...

So with the following code:
![image](https://user-images.githubusercontent.com/58780956/70633797-67e11180-1c31-11ea-9b52-2867cc922b01.png)

He does place the brick block on the given position, but the text isn't printed in the game chat. Now if you go on and look the server chat, you can see the command is printed there:
![image](https://user-images.githubusercontent.com/58780956/70634042-d1f9b680-1c31-11ea-8924-a1164f1aefb8.png)

In the start I had the same problem with the mc.setBlock() function, but then I did "mvtp [playerName] world" and I teleported to another world and then I was able to see the block. It's only the mc.postToChat() that isn't working for now. 

Does anyone of you guys know how i'm able to fix this problem? 

Kind regards

**Comment by martinohanlon** [comment]
Are you sure the message isnt appearing on the game chat? It only stays on the screen for a few seconds.

**Comment by RobinGoussey** [comment]
No, I have the same problem, but I figured it is because I am using LuckPerms. So whenever I have luckperm, the post to chat no longer works.

**Comment by RobinGoussey** [comment]
The issue is external. Our permissions plugin had bukkit.broadcast disabled, causing the plugin somehow to not show it. Giving the default players the permission to broadcast fixed the issue.

**Comment by Fishh40** [comment]
> Are you sure the message isnt appearing on the game chat? It only stays on the screen for a few seconds.

It wasn't showing, but we did find the answer already, it had something todo with the plugin "Luckperms". 

First I did delete it, but afterwards it seemed that it was just a specific permission that needed to be alterded. 

But thanks for your reply!
