### ISSUE TITLE
RasberryJuice and mpci modified for minecraft java server 1.15.1 with new Material names

### ISSUE THREAD

**Issue by sprouviere** [zhuowei/RaspberryJuice#93]
Hello,

I inform you of the modifications I did on raspberryJuice and mcpe.

I wanted to use new Minecraft blocks with bukkit - spigot name : [https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html](https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html)

I've modified the RemoteSession.java file in the RaspberryJuice 1.12 and give a new name to the  plugin :  pythondsminecraft.jar. ( because world.setBlocks and world.setBlock have been modified and are no more compatible with id numbers : Material blockType = Material.getMaterial(args[3]); 
and a lot of world.setxxxx have been added too ...

I've modified the minecraft.py file - class Minecraft only and called it mcse (MineCraftSErver) in this way.

Because of the different BlockData, I've created different python modules (setBlock... setGate ...) I'm a  one moth java programmer experience (began to learn java to use the plugin with 1.15 Minecraft version)  and it's too difficult for me to program a unique SetBlock creation for the different BlockData.  Heritage notions are complex in bukkit ...

You can have a look to the result here  (see the video) and dowload the files (Sorry I'm not familiar with Gitub) :
[http://pinet.rouviere.free.fr/description_mcse/index.html](http://pinet.rouviere.free.fr/description_mcse/index.html)

I hope you won't be angry, I'm not a thief, I'm not intented to harm. 
I 'm intend to adapt Entity function too  (getTypeId is depreciated ...) I'd like to create a cat !

The most important : thanks for your work !

**Comment by martinohanlon** [comment]
Thanks for letting us know.

Similar actions have been taken by others. Take a look at - https://github.com/zhuowei/RaspberryJuice/pull/84#issuecomment-544295161

I wont be creating a `RaspberryJuice2` because of the issue outlined.

Perhaps get in touch with @minecraftDawn

**Comment by acs** [comment]
@sprouviere has you evolved your work? I am trying to find the options all we have to adapt Rasperry PI to materials: https://github.com/zhuowei/RaspberryJuice/pull/84#issuecomment-626345622

Let's try to find together this solution!

**Comment by sprouviere** [comment]
Hi,
I understand that you would like to use Material on Minecraft raspberry py. I know that minecraft game is free on raspberry but I don't know if it is a recent version. I've never try to program with python in minecraft's raspberry.

I use a local bukkit-spigot server (installed on my pc or on a raspberry) and a java pc minecraft version.

I have modified raspberryJuice.jar plugin and rename it pythondsminecraft. jar 
- to use with MATERIAL instead of ID - using id is no more possible with my plugin.  
- play on a spigot minecraft SERVER 1.15.1 and later 

I have modified the mcpi python library too, and rename it mcse (MineCraft SErver) 

You can find .jar , python library to download , tutoriel to use with block name and python examples (in french, sorry) on 
[my_website](http://pinet.rouviere.free.fr/description_mcse/installation__tlchargement__download.html)
It is not the last one (I am working on the ability to add entity by name like cat, horse, ... with their properties ) but it works and you can try it : same way to use as rapberryjuice and mcpi.

The class sources are includes in the jar file and the python files are readable. 
All I've done is simple, I've just change "id number" in material. You can compare with originals.
If you can't read it just ask to have them.
I replace "depreciated" bukkit fonctions by news ...

What do you mean by " Rasperry PI to materials" ?

**Comment by lasteamlab** [comment]
I've created a git repository with your up-to-date mcse and am calling it mcpi2
If you would be interested in sharing your Java files with me, I will do the same with the .jar

I'll link everything back to your page, but provide English instructions and a place for collaboration.

https://github.com/lasteamlab/mcpi2

**Comment by sprouviere** [comment]
It's a good idea !
And writed it in a good english (mine is so poor !)  would be perfect !

About java sources, I thought they where inside .jar and I've just discovered that they are not added !!!
Sorry, I'm begginer in java programming and in eclipse using.

I haven't got anymore the java sources of the 2.0 version (actualy published) but I'm about to post a 2.1 version on my website (test on rabbit and wolf to do before ...)  and I have already added java sources in a specific and separate download link the update.

I'll inform you here when It will be in line. ... few days 
So you could have all the files you need.

**Just a remark;** I don't care to rename mcse in mcpi2 but "mcpi" means MineCraft for raspberry PI and I'm not sure that my python library is compatible with the raspeberry PI minecraft version. did you test it ?
That'a why I chose to rename it in mcse (Minecraft server) because a MineCraft SEver is necessary to use it ... 
I didn't want to make confused raspberry PI users ....

**Comment by lasteamlab** [comment]
I'll give that a thought.  I was trying to tie it back to the original in an obvious way.  I also grabbed MinecraftDawn's server and am doing some edits right now, such as passing a player id instead of needing to call an entity.  I'll merge your updates (I hadn't done any work with calling entities by name MinecraftDawn only calls blocks by name).  I was trying to overload classes so the mcpi still works.  I'm not going to try to the point of making everything ugly, though.

My longterm goal is to get everything in the Bukkit API hooked into the server jar and callable through python.  I think you've done a ton of work towards that already.

Also your English is much better than my French.

**Comment by sprouviere** [comment]
Hi,
Version 2.1 is on line : [http://pinet.rouviere.free.fr/description_mcse/index.html](url)

You'll find the complete  java project (with the .java and the jar ressources : Craftbukkit and mincraft server) : [http://pinet.rouviere.free.fr/description_mcse/sources_java.html](url)

I've added an example part : [http://pinet.rouviere.free.fr/description_mcse/exemples.html](url)

In the mcse description part [http://pinet.rouviere.free.fr/description_mcse/tutoriel_utilisation_mcse__librairie_python.html](url) I've added animals - entity functions.
The explanations are in french but each function has an example of use in Python ...

Your [https://github.com/lasteamlab/mcpi2](url) is a good work.
