### ISSUE TITLE
python ValueError: invalid literal for int() with base 10: ''

### ISSUE THREAD

**Issue by cainiaoxuyuanwei** [zhuowei/RaspberryJuice#94]

**Comment by cainiaoxuyuanwei** [comment]
![Snipaste_2020-02-03_23-09-35](https://user-images.githubusercontent.com/12911953/73664513-810ab980-46da-11ea-9b32-4ffe8d039bd9.jpg)

**Comment by cainiaoxuyuanwei** [comment]
![Snipaste_2020-02-03_23-09-35](https://user-images.githubusercontent.com/12911953/73664569-997ad400-46da-11ea-98cf-bbca63940f63.jpg)

**Comment by cainiaoxuyuanwei** [comment]
W:\file\python\py_mc_demo01\Scripts\python.exe W:/file/python/py_mc_demo01/main.py
Traceback (most recent call last):
  File "W:/file/python/py_mc_demo01/main.py", line 4, in <module>
    postion = mc.player.getTilePos()
  File "W:\file\python\py_mc_demo01\mcpi\minecraft.py", line 72, in getTilePos
    return CmdPositioner.getTilePos(self, [])
  File "W:\file\python\py_mc_demo01\mcpi\minecraft.py", line 44, in getTilePos
    return Vec3(*list(map(int, s.split(","))))
ValueError: invalid literal for int() with base 10: ''

进程完成，退出码 1

**Comment by martinohanlon** [comment]
I cannot recreate the error using Minecraft 1.12.2 and RaspberryJuice v1.12.1

Can you provide more information.
- your complete code listing, not just a single line snippet
- the version of minecraft, raspberry pi juice you are using
- what you are doing when you receive the error 
- whether any errors are reported in the server console
