### ISSUE TITLE
Is there a pip package for mcpi modded lib?

### ISSUE THREAD

**Issue by acs** [zhuowei/RaspberryJuice#98]
I am talking about the python modded lib at:

https://github.com/zhuowei/RaspberryJuice/tree/master/src/main/resources/mcpi/api/python/modded/mcpi

From a quick search:

https://pypi.org/search/?q=mcpi&o=

it seems this modded python lib does not exist. So using it is not easy for Python developers to enjoy the extended API.

Do you have any plans about releasing it?

**Comment by martinohanlon** [comment]
The mcpi package on pypi (https://pypi.org/project/mcpi/) does support Raspberry Juice.

The github repo provides a readme - https://github.com/martinohanlon/mcpi

**Comment by martinohanlon** [comment]
This did remind me to release a new version of mcpi which includes all the additional functions which went into RaspberryJuice v1.12.1. Done. Thanks

```
pip3 install mcpi --upgrade
```

Will pull down mcpi 1.2.0
